<?php

/**
 * @file
 * Provides a demo store for Commerce.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
//function arena_form_commerce_order_item_add_to_cart_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //dpm($form_state);
  //$form['submit']['#value'] = '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> '.t("Buy");
  //$form['#attributes']['class'][] ='form-inline';
  //$test = $form_state->getBuildInfo();
  //echo $test;
//}

function arena_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //dpm($form_state);
  //$form['submit']['#value'] = '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> '.t("Buy");
  $form['#attributes']['class'][] ='well col-sm-12 col-md-8 col-md-offset-2';
  //$test = $form_state->getBuildInfo();
  //echo $test;
}

function arena_form_user_login_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //dpm($form_state);
  //$form['submit']['#value'] = '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> '.t("Buy");
  $form['#attributes']['class'][] ='well col-sm-12 col-md-6 col-md-offset-3';
  //$test = $form_state->getBuildInfo();
  //echo $test;
}

function arena_form_user_pass_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  //dpm($form_state);
  //$form['submit']['#value'] = '<span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> '.t("Buy");
  $form['#attributes']['class'][] ='well col-sm-12 col-md-6 col-md-offset-3';
  //$test = $form_state->getBuildInfo();
  //echo $test;
}

function arena_form_views_exposed_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  
    //dpm($form_state);
if ($form['#id'] == 'views-exposed-form-product-search-page-1') {
    
    $form['keys']['#size'] = 12;  // define size of the textfield
   
    //$form['#attributes']['class'][] ='navbar-form navbar-center';

  }
}
